version: '2'
services:
  ldap:
    image: osixia/openldap:1.1.11
    container_name: upem-api-ldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Univ MLV."
      LDAP_DOMAIN: "univ-mlv.fr"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      #ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /root/ldif
      #- ./docker/image/ldap/ldap:/var/lib/ldap
      #- ./docker/image/ldap/slapd.d:/etc/ldap/slapd.d
      - ./docker/image/ldap/ldif:/root/ldif
    ports:
      - "389:389"
      - "636:636"
    domainname: "univ-mlv.fr"
    hostname: "univ-mlv.fr"
  ldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: upem-api-ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "3080:80"
    depends_on:
      - ldap
  upem-api:
    build: ./docker/image/php
    container_name: upem-api
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - ldap
