services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\Ldap\LdapService:
        arguments:
            - '%ldap.host%'
            - '%ldap.dn%'

    AppBundle\Service\StudentService:
        arguments:
            - '@AppBundle\Service\Ldap\LdapService'
