parameters:
    ldap.host: 'ldap://vmldapetud1.u-pem.fr/'
    ldap.dn: 'ou=Users,ou=Etudiant,dc=univ-mlv,dc=fr'
    ade.host: 'https://edt.u-pem.fr'
    ade.login: 'visuedt'
    ade.password: 'visuedt'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\StudentService:
        arguments:
            - '%kernel.environment%'
            - '%ldap.host%'
            - '%ldap.dn%'
